using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace UisSubsea.RovTopside.Data
{
    public class JoystickStateStore
    {
        /// <summary>
        /// This class serves the purpose of always having the
        /// most recent state of each joystick.
        /// 
        /// The joystick state listeners updates this class when 
        /// an interrupt is generated by one of the joysticks.
        /// 
        /// The communication server fetches the packages stored 
        /// here, and transmits them down to the CCU for further processing.
        /// </summary>

        public byte[] Main { get; private set; }
        public byte[] ManipulatorLeft { get; private set; }
        public byte[] ManipulatorRight { get; private set; }

        public JoystickStateStore()
        {
            Main = new byte[0];
            ManipulatorLeft = new byte[0];
            ManipulatorRight = new byte[0];
        }

        public void StoreState(byte[] statePacket, JoystickType type)
        {
            switch(type)
            {
                case(JoystickType.MainController) :
                    Main = statePacket;
                    break;
                case (JoystickType.ManipulatorLeft) : 
                    ManipulatorLeft = statePacket;
                    break;
                case (JoystickType.ManipulatorRight) :
                    ManipulatorRight = statePacket;
                    break;
            }
        }
    }
}
